<!DOCTYPE html>
<html>
<head>
  <title>Sample size calculator</title>
  <meta charset="utf-8">
  <meta name="description" content="Sample size calculator">
  <meta name="author" content="Marc Mari-Dell'Olmo">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  <link rel=stylesheet href="./assets/css/ribbons.css"></link>

  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <hgroup class="auto-fadein">
    <h1>Sample size calculator</h1>
    <h2>Two independent means</h2>
    <p>Marc Mari-Dell'Olmo<br/>CIBERESP</p>
  </hgroup>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>Shiny app description</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>This Shiny app provides sample size calculations for two-sided two-sample t-tests when the variances of the two groups (populations) are assumed to be equal.</p></li>
<li><p>This is the traditional two-sample t-test (Fisher, 1925). In this procedure, the assumed difference between means is specified by entering the difference directly. The design corresponding to this test procedure is sometimes referred to as a parallel-groups design.</p></li>
<li><p>This design is used in situations such as the comparison of the income level of two regions, the nitrogen content of two lakes, or the effectiveness of two drugs. </p></li>
<li><p>There are several statistical tests available for the comparison of the center of two populations. This procedure is specific to the two-sample t-test assuming equal variance. </p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-2" style="background:;">
  <hgroup>
    <h2>Parameters values to enter</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>Alpha: This is the probability of obtaining a false positive with the statistical test. That is, it is the probability of rejecting a true null hypothesis. The null hypothesis is that the means are equal.</li>
<li>Beta: This is the probability of obtaining a false negative with the statistical test. That is, it is the probability of accepting a false null hypothesis.).</li>
<li>Group 2 size/Group 1 size ratio: set a value for the ratio of Group 2 size to Group 1 size, and then this calculator determines the needed Group 1 and Group 2 size, with this ratio, to obtain the desired power.</li>
<li>Estimated common standard deviation: This is the assumed standard deviation for both the Group 1 population and the Group 2 population.</li>
<li>Minimun expected difference: Enter a value for the assumed difference between the means of Groups 1 and 2. This difference is the difference at which the design is powered to reject equal means.</li>
<li>Dropout rate: Percentage of the expected number of subjects dropped out at the end of the study. For example, if you enter 0.1 the final adjusted taking into account a dropout rate of 10%.</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-3" style="background:;">
  <hgroup>
    <h2>Example</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>With these values: Alpha = 0.05, Beta = 0.2, Ratio = 2, Common Standard deviation = 10, Minimum expected difference = 1, Dropout rate = 0.1</p></li>
<li><p>This Shiny app uses the following R syntax:</p></li>
</ul>

<pre><code class="r">library(samplesize)
power = 1-0.2
sample &lt;- n.ttest(power = power, alpha = 0.05, mean.diff = 1, sd1 = 10, k = 2, design = &quot;unpaired&quot;, 
                  fraction = &quot;unbalanced&quot;, variance = &quot;equal&quot;)
ceiling(sample[[2]]/(1-0.1))
</code></pre>

<pre><code>## [1] 1309
</code></pre>

<pre><code class="r">ceiling(sample[[3]]/(1-0.1))
</code></pre>

<pre><code>## [1] 2618
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-4" style="background:;">
  <hgroup>
    <h2>Result</h2>
  </hgroup>
  <article data-timings="">
    <p>The result is the folowing paragraph that you can copy-paste to your project documentation or paper:</p>

<p>Accepting an alpha risk of 0.05 and a beta risk of 0.2 in a two-sided test, <strong>1309</strong> subjects are necessary in first group and <strong>2618</strong> in the second to recognize as statistically significant a difference greater than or equal to 1 units. The common standard deviation is assumed to be 10. It has been anticipated a drop-out rate of 10%.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='Shiny app description'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='Parameters values to enter'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='Example'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='Result'>
         4
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>